DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS finds;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS building_years;
DROP TABLE IF EXISTS building_attributions;
DROP TABLE IF EXISTS buildings;
DROP TABLE IF EXISTS years;